import streamlit as st
import pdfplumber
import re
import json

FRAUD_WORDS = [
    "fraud", "staged", "inconsistent", "fake", "suspicious",
    "intentional", "planned accident"
]

st.set_page_config(page_title="Insurance Claim AI Agent", layout="centered")
st.title("🚗 Autonomous Insurance Claims Processing Agent")
st.write("Upload FNOL insurance PDFs and get automated claim routing.")

# ---------- PDF TEXT EXTRACTION ----------
def extract_text_from_pdf(file):
    text = ""
    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:
            if page.extract_text():
                text += page.extract_text() + "\n"
    return text

# ---------- FIELD FINDER ----------
def find_field(pattern, text):
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        value = match.group(1).strip()
        # Remove labels accidentally captured
        if len(value) < 3 or value.isupper():
            return None
        return value
    return None

# ---------- FIELD EXTRACTION ----------
def extract_fields(text):
    fields = {}
    fields["policy_number"] = find_field(r"POLICY NUMBER[:\s]*([A-Z0-9\-]{6,})", text)
    fields["insured_name"] = find_field(r"NAME OF INSURED.*?:\s*(.*)", text)
    fields["date_of_loss"] = find_field(r"DATE OF LOSS.*?:?\s*([0-9/:-]+)", text)
    fields["location"] = find_field(r"LOCATION OF LOSS.*?:\s*(.*)", text)
    fields["description"] = find_field(r"DESCRIPTION OF ACCIDENT.*?:\s*(.*)", text)
    estimate = find_field(r"ESTIMATE AMOUNT[:\s]*([$0-9,]+)", text)
    if estimate:
        estimate = estimate.replace("$", "").replace(",", "")
        fields["estimate_amount"] = float(estimate)
    else:
        fields["estimate_amount"] = None
    fields["claim_type"] = "injury" if "injury" in text.lower() else "vehicle"
    return fields

# ---------- MISSING FIELDS ----------
def find_missing(fields):
    required = [
        "policy_number",
        "insured_name",
        "date_of_loss",
        "location",
        "description",
        "estimate_amount",
        "claim_type"
    ]
    return [field for field in required if not fields.get(field)]

# ---------- ROUTING ----------
def decide_route(fields, missing):
    description = (fields.get("description") or "").lower()
    estimate = fields.get("estimate_amount")
    if missing:
        return "Manual Review", "Some mandatory fields were missing"
    if any(word in description for word in FRAUD_WORDS):
        return "Investigation", "Fraud-related risk terms detected in description"
    if fields["claim_type"] == "injury":
        return "Specialist Queue", "Claim involves injury"
    if estimate and estimate < 25000:
        return "Fast-track", "Damage estimate is low risk"
    return "Manual Review", "Default routing"

def calculate_confidence(fields, missing):
    total = len(fields)
    filled = total - len(missing)
    return round((filled / total) * 100, 2)

def generate_report(fields, missing, route, reason, confidence):
    report = f"""
INSURANCE CLAIM AI REPORT
----------------------------

Extracted Fields:
{json.dumps(fields, indent=4)}

Missing Fields:
{missing if missing else "None"}

Recommended Route:
{route}

Reasoning:
{reason}

Confidence Score:
{confidence}%

Generated by Autonomous Claims AI System
"""
    return report

# ---------- UI ----------
uploaded_files = st.file_uploader("📄 Upload FNOL PDFs", type="pdf", accept_multiple_files=True)

if uploaded_files:
    for file in uploaded_files:
        st.divider()
        st.subheader(f"Processing: {file.name}")
        with st.spinner("Analyzing claim..."):
            text = extract_text_from_pdf(file)
            fields = extract_fields(text)
            missing = find_missing(fields)
            route, reason = decide_route(fields, missing)
            confidence = calculate_confidence(fields, missing)
            report_text = generate_report(fields, missing, route, reason, confidence)

            result = {
                "extractedFields": fields,
                "missingFields": missing,
                "recommendedRoute": route,
                "reasoning": reason,
                "confidenceScore": f"{confidence}%"
            }

        st.success("Done ✅")
        st.subheader("📋 Extracted Fields")
        st.json(fields)
        st.subheader("⚠ Missing Fields")
        st.write(missing if missing else "None")
        st.subheader("🚦 Recommended Route")
        st.write(f"**{route}**")
        st.subheader("🧠 Reasoning")
        st.write(reason)
        st.subheader("📄 Claim Summary Report")

        st.download_button(
            label="⬇ Download Claim Report",
            data=report_text,
            file_name=f"{file.name}_AI_Report.txt",
            mime="text/plain"
        )


        # 🔽 Download JSON
        st.download_button(
            label="⬇ Download Result JSON",
            data=json.dumps(result, indent=4),
            file_name=f"{file.name}_result.json",
            mime="application/json"
        )
